main/urls.py
from django.urls import path
from main import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('', views.index, name="index"),
    path('blog/', views.blog, name="blog"),
    path('blog/post/<int:post_id>/', views.post, name="post"),
    path('contact/', views.contact, name="contact"),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from ckeditor.fields import RichTextField


# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=300)
    content = RichTextField()
    posted_date = models.DateTimeField(auto_now_add=True)


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.TextField()


class WorkExperience(models.Model):
    title = models.CharField(max_length=250)
    workplace = models.CharField(max_length=200)
    discription = models.TextField()
    starting_date = models.DateField()
    ending_date = models.DateField()


class Certificate(models.Model):
    title = models.CharField(max_length=250)
    discription = models.TextField()
    issue_date = models.DateField()
    url = models.URLField()


class Project(models.Model):
    title = models.CharField(max_length=250)
    discription = models.TextField()
    starting_date = models.DateField()
    ending_date = models.DateField()
    url = models.URLField(blank=True)

main/forms.py
from django import forms
from main.models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'message']

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator

from main.models import Post, WorkExperience, Project, Certificate

from main.forms import ContactForm

from django.core.mail import EmailMessage
from django.conf import settings as conf_settings

from django.contrib import messages


# Create your views here.
def index(request):
    work_experience = WorkExperience.objects.all()
    project = Project.objects.all()
    certificate = Certificate.objects.all()

    context = {'work_experience': work_experience, 'project': project, 'certificate': certificate}

    return render(request, 'main/index.html', context)


def blog(request):
    posts = Post.objects.all().order_by('-posted_date')
    paginator = Paginator(posts, 2)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'page_obj': page_obj}
    return render(request, 'main/blog.html', context)


def post(request, post_id=None):
    post = get_object_or_404(Post, id=post_id)
    context = {'post': post}
    return render(request, 'main/post.html', context)


def contact(request):
    form = ContactForm(request.POST or None)
    if form.is_valid():
        instance = form.save(commit=False)

        name = instance.name
        email = instance.email
        message = instance.message

        EmailMessage(
            'New message from %s' %name,
            'Hi admin, new message form this email address: %s\n\n Message: %s' %(email, message),
            
        ).send()

        form.save()

        messages.success(request, 'Your message has been sent!')

        return redirect('contact')

    context = {'form': form}
    return render(request, 'main/contact.html', context)
    

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

        <!-- Google font section -->
        {% block font %}
            <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
            <link href="https://fonts.googleapis.com/css2?family=Sacramento&display=swap" rel="stylesheet"> 
            <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet"> 
        {% endblock %}

        <!-- CSS section -->
        {% block css %}
            <link rel="stylesheet" href="{% static 'main/style.css' %}">
        {% endblock %}

        <!-- Fontawesome icons -->
        <script src="https://kit.fontawesome.com/5a27b7711c.js" crossorigin="anonymous"></script>

        <title>{% block title %}{% endblock %}</title>

        <!-- Style section -->
        {% block style %}{% endblock %}

        <!-- Script section -->
        {% block script %}{% endblock %}

    </head>

    <body>
        <!-- Content section -->
        {% block content %}{% endblock %}
        

        <!-- Optional JavaScript; choose one of the two! -->

        <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

         {% comment %} Option 2: jQuery, Popper.js, and Bootstrap JS {% endcomment %}
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
        
    </body>
</html>

main/templates/main/blog.html
{% extends 'main/index.html' %}

{% block title %}Mysite | Blog{% endblock %}

{% block main-content %}
<div class="container">
    <h1 class="text-center mt-5"><b>All Posts</b></h1>
    <div class="mt-5">
        {% for post in page_obj %}
            <h2><a href="{% url 'post' post.id %}" class="text-body">{{ post.title }}</a></h2>
            <p class="text-muted"><small>{{ post.posted_date|date:"F d, Y" }}</small></p><hr>
        
        {% endfor %}
    </div>
</div>


<div class="container">
    <div class="row mt-5 mb-n2">
        <div class="col-12 text-center text-muted">
            <p><span>Showing page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}</span></p>
        </div>
    </div>

    <ul class="pagination pagination-sm mb-5 justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1">&laquo; First</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a></li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if page_obj.number == num %}
                <li class="page-item active"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">Last &raquo;</a></li>
        {% endif %}
    </ul>
</div>
{% endblock %}

main/templates/main/contact.html
{% extends 'main/index.html' %}
{% load crispy_forms_tags %}

{% block title %}Mysite | Contact{% endblock %}

{% block style %}
<style>
    .asteriskField {
        color: red;
    }
</style>
{% endblock %}

{% block main-content %}

{% if messages %}
    {% for message in messages %}
        <div class="container-fluid alert alert-{{ message.tags }}">
            <div class="container message">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <span id="id_message">{{ message }}</span>
            </div>
        </div>
    {% endfor %}
{% endif %}

<div class="container mt-5 mb-5" style="max-width: 600px;">
    <h1 class="text-center mb-5"><b>Contact Form</b></h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-success mt-3">Submit</button>
    </form>
</div>


{% endblock %}

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}Mysite | Home{% endblock %}

{% block content %}

<!-- Navbar section -->
<nav class="navbar navbar-expand-md">
    <!-- Brand -->
    <a class="navbar-brand ml-2 ml-lg-5" style="color: #d20ce4;">Akhilesh Yadav</a>
  
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
        <i class="navbar-toggler-icon fas fa-bars"></i>
    </button>
  
    <!-- Navbar links -->
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <ul class="navbar-nav ml-lg-auto ml-2 mr-lg-5">
            <li class="nav-item"><a class="nav-link" href="{% url 'index' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'blog' %}">Blog</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'contact' %}">Contact</a></li>
        </ul>
    </div>
</nav>

{% block main-content %}
<div class="container">
    <div class="row mt-5 mb-5">
        <div class="col-lg-2 col-md-6 col-sm-6">
        {% load static %}
            <img src="{% static 'main/images/Akhil.JPG' %}" alt="My photo" class="img-fluid rounded" width="240px">
        </div>

        <div class="col-lg-10 col-md-6 col-sm-6">
            <h1>Akhilesh Yadav</h1>
            <p style="font-size: large;">Hi ! Everyone This is Akhilesh Yadav From Gorakhpur-UttarPradesh.My Hobby Is To Playing Cricket.I m Student Of InFromation Technology Of B.tech Department From Chaudhary Charan Singh University,Meerut(U.P).I Have much more interest in the filled of Programming.My Favourite Programming language is Python.I Also know Much more About HTML,CSS,BOOTSTRAP4,Javascript,PHP  etc.</p>
        </div>

    </div>
</div>


<div class="container mt-5">
    <h1 class="text-center mb-5">Work Experince</h1>
    
    {% for work in work_experience %}
    <div>
        <h2>{{ work.title }}</h2>
        <p><small>{{ work.workplace }}</small></p>
        <p>{{ work.discription }}</p>
        <p><small>Starting date: {{ work.starting_date|date:"F d, Y" }} | Ending date: {{ work.ending_date|date:"F d, Y" }}</small></p>
    </div><hr>
    {% endfor %}

</div>

<div class="container mt-5">
    <h1 class="text-center mb-5">Certificates</h1>
    
    {% for cert in certificate %}
    <div>
        <h2>{{ cert.title }}</h2>
        <p><small>Url: <a href="{{ cert.url }}">{{ cert.url }}</a></small></p>
        <p>{{ cert.discription }}</p>
        <p><small>Issue date: {{ cert.issue_date|date:"F d, Y" }}</small></p>
    </div><hr>
    {% endfor %}

</div>

<div class="container mt-5 mb-5">
    <h1 class="text-center mb-5">Projects</h1>
    
    {% for proj in project %}
    <div>
        <h2>{{ proj.title }}</h2>

        {% if proj.url %}
            <p><small>Url: <a href="{{ proj.url }}">{{ proj.url }}</a></small></p>
        {% endif %}

        <p>{{ proj.discription }}</p>
        <p><small>Starting date: {{ proj.starting_date|date:"F d, Y" }} | Ending date: {{ proj.ending_date|date:"F d, Y" }}</small></p>
    </div><hr>
    {% endfor %}

</div>
{% endblock %}

<!-- Footer section -->
<div class="footer pt-5">
    <div class="container-lg">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <p class="text-center" style="font-size: 26px; margin-bottom: -1px;">Made with <i class="fas fa-heart" style="font-size: 18px; color: red;"></i></p>
                <ul class="list-unstyled list-inline social text-center">
                    <li class="list-inline-item mr-3"><a href="https://github.com/Akhilesh9376" target="_blank"><i class="fab fa-github"></i></a></li>
                    <li class="list-inline-item mr-3"><a href="https://www.facebook.com/akhilesh.yadav.18488169" target="_blank"><i class="fab fa-facebook"></i></a></li>
                    <li class="list-inline-item mr-3"><a href="https://www.linkedin.com/in/akhilesh-yadav-5b119b1ba/" target="_blank"><i class="fab fa-linkedin-in"></i></a></li>
                    <li class="list-inline-item"><a href="mailto:akhileshyadavkokta@gmail.com" target="_blank"><i class="far fa-envelope"></i></a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock %}

 <footer class="footer">
      <div class="container">
      <p>Made With <span> <i class="fas fa-heart" style="font-size: 18px; color: red;"></i></span></p>
      <ul class="list-unstyled list-inline social text-center">
        <li class="list-inline-item mr-3"><a href="https://github.com/Akhilesh9376/akhilesh-yadav" target="_blank"><i class="fab fa-github"></i></a></li>
        <li class="list-inline-item mr-3"><a href="https://www.instagram.com/akhill_90/" target="_blank"><i class="fab fa-instagram"></i></a></li>
        <li class="list-inline-item mr-3"><a href="https://www.facebook.com/akhilesh.yadav.18488169" target="_blank"><i class="fab fa-facebook"></i></a></li>
        <li class="list-inline-item"><a href="mailto:akhileshyadavkokta1@gmail.com" target="_blank"><i class="far fa-envelope"></i></a></li>
    </ul>
      </div>
    </footer>

main/templates/main/post.html
{% extends 'main/index.html' %}

{% block title %}Mysite | {{ post.title }}{% endblock %}

{% block main-content %}

<div class="container">
    <div class="mt-5 mb-5">
        <h1><b>{{ post.title }}</b></h1>
        <p class="text-muted"><small>{{ post.posted_date|date:"F d, Y" }}</small></p>
        <p class="mt-3">{{ post.content|safe }}</p>
        
    </div>
</div>

{% endblock %}